import type { Metadata } from "next";
// import localFont from "next/font/local";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        {/* <main className="w-full flex">{children}</main> */}
        <div className="flex rounded-2xl overflow-hidden w-full h-[100dvh] mx-auto relative my-auto">
          <div className="h-full relative w-full overflow-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
