import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import NavbarLogged from "@/components/NavbarLogged";
import { ChevronDown } from "lucide-react";
import { AppSidebar } from "@/components/app-sidebar";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <SidebarProvider>
          <AppSidebar />
          {/* <main className="w-full flex">{children}</main> */}
          <div className="flex rounded-2xl overflow-hidden w-full h-[100dvh] mx-auto relative my-auto">
            <div className="h-full relative w-full overflow-auto">
              <NavbarLogged />
              {children}
            </div>
            <div className="flex-none hidden xl:block relative w-[300px] border-l h-full">
              <nav className="sticky z-50 top-0 left-0 w-full border-b h-20 bg-[#111010]/60 flex items-center backdrop-blur px-4">
                <div className="w-full flex justify-end items-center gap-4">
                  <p className="text-sm rounded-full h-12 aspect-square bg-color1" />
                  <div>
                    <h1 className="text-lg">John Doe</h1>
                    <p className="text-xs text-[#6f6f72]">Admin</p>
                  </div>
                  <ChevronDown size={16} />
                </div>
              </nav>

              <div className="p-4">
                <div className="flex w-full items-end justify-between">
                  <p>Notifications</p>
                  <p className="text-xs text-color1">See all</p>
                </div>
              </div>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
